apiVersion: k8s.ovn.org/v1
kind: RouteAdvertisements
metadata:
  name: vrf-lite-cudn
spec:
  targetVRF: auto
  advertisements:
    - PodNetwork
  nodeSelector: {}
  frrConfigurationSelector:
    matchLabels:
      use-for-advertisements: "true"
  networkSelectors:
    - networkSelectionType: ClusterUserDefinedNetworks
      clusterUserDefinedNetworkSelector:
        networkSelector:
          matchLabels:
            advertise-external-secondary-vrf: "true"
