apiVersion: v1
kind: Pod
metadata:
  name: network-tools
  namespace: tenant1
  labels:
    app: network-tools
    tenant: tenant1
spec:
  containers:
    - name: network-tools
      image: quay.io/openshift/origin-network-tools:latest
      command: ["/bin/bash", "-c", "sleep infinity"]
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: network-tools
  namespace: tenant2
  labels:
    app: network-tools
    tenant: tenant2
spec:
  containers:
    - name: network-tools
      image: quay.io/openshift/origin-network-tools:latest
      command: ["/bin/bash", "-c", "sleep infinity"]
  restartPolicy: Always
