frr version 10
frr defaults traditional
hostname r1
!
vrf tenant1
 exit-vrf
!
vrf tenant2
 exit-vrf
!
interface eth1 vrf tenant1
 ip address 172.19.0.1/24
!
interface eth2 vrf tenant2
 ip address 172.19.0.1/24
!
interface eth3 vrf tenant1
 ip address 10.100.2.1/24
!
interface eth4 vrf tenant2
 ip address 10.200.2.1/24
!
router bgp 65000 vrf tenant1
 bgp router-id 172.19.0.1
 no bgp ebgp-requires-policy
 neighbor 172.19.0.10 remote-as 65001
 !
 address-family ipv4 unicast
  redistribute connected
  neighbor 172.19.0.10 activate
 exit-address-family
!
router bgp 65000 vrf tenant2
 bgp router-id 172.19.0.1
 no bgp ebgp-requires-policy
 neighbor 172.19.0.10 remote-as 65001
 !
 address-family ipv4 unicast
  redistribute connected
  neighbor 172.19.0.10 activate
 exit-address-family
!
line vty
!
end
