# BGP configuration for worker node
# Node-specific to allow proper source address configuration
---
apiVersion: frrk8s.metallb.io/v1beta1
kind: FRRConfiguration
metadata:
  name: bgp-clos-worker
  namespace: openshift-frr-k8s
  labels:
    use-for-advertisements: "true"
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: bgp-worker-0.labs.ovn-k8s.local
  bgp:
    routers:
      - asn: 65000
        vrf: default
        id: 192.168.255.2
        neighbors:
          - address: 192.168.255.11
            asn: 65001
            ebgpMultiHop: true
            bfdProfile: default
            disableMP: true
            sourceaddress: 192.168.255.2
            toReceive:
              allowed:
                mode: all
            toAdvertise:
              allowed:
                mode: all
          - address: 192.168.255.12
            asn: 65002
            ebgpMultiHop: true
            bfdProfile: default
            disableMP: true
            sourceaddress: 192.168.255.2
            toReceive:
              allowed:
                mode: all
            toAdvertise:
              allowed:
                mode: all
    bfdProfiles:
      - name: default
