frr version 10
frr defaults traditional
hostname leaf1
!
interface lo
 ip address 192.168.255.11/32
!
interface eth1
 ip address 10.10.1.1/31
!
interface eth2
 ip address 10.0.1.0/31
!
interface eth3
 ip address 10.0.1.2/31
!
ip route 192.168.255.1/32 10.0.1.1
ip route 192.168.255.2/32 10.0.1.3
!
router bgp 65001
 bgp router-id 192.168.255.11
 no bgp ebgp-requires-policy
 neighbor 10.10.1.0 remote-as 65413
 neighbor 192.168.255.1 remote-as 65000
 neighbor 192.168.255.1 ebgp-multihop 2
 neighbor 192.168.255.1 update-source lo
 neighbor 192.168.255.1 bfd
 neighbor 192.168.255.2 remote-as 65000
 neighbor 192.168.255.2 ebgp-multihop 2
 neighbor 192.168.255.2 update-source lo
 neighbor 192.168.255.2 bfd
 !
 address-family ipv4 unicast
  redistribute connected
  neighbor 10.10.1.0 activate
  neighbor 192.168.255.1 activate
  neighbor 192.168.255.2 activate
 exit-address-family
!
line vty
!
end
