---
apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: evpn-l3
  labels:
    evpn: enabled
    tenant: evpn-l3
spec:
  namespaceSelector:
    matchLabels:
      network: evpn-l3
  network:
    topology: Layer2
    layer2:
      role: Primary
      subnets:
        - 10.60.0.0/24
      ipam:
        lifecycle: Persistent
    transport: EVPN
    evpn:
      vtep: evpn-vteps
      macVRF:
        vni: 200
      ipVRF:
        vni: 201
