frr version 10
frr defaults traditional
hostname ext-host
!
interface lo
 ip address 192.168.255.13/32
!
interface lo-vtep
 ip address 100.64.0.13/32
!
interface eth1
 ip address 10.0.3.1/31
!
ip route 192.168.255.11/32 10.0.3.0
ip route 192.168.255.12/32 10.0.3.0
!
router bgp 65003
 bgp router-id 192.168.255.13
 no bgp ebgp-requires-policy
 neighbor 192.168.255.11 remote-as 65001
 neighbor 192.168.255.11 ebgp-multihop 2
 neighbor 192.168.255.11 update-source lo
 neighbor 192.168.255.11 bfd
 neighbor 192.168.255.12 remote-as 65002
 neighbor 192.168.255.12 ebgp-multihop 2
 neighbor 192.168.255.12 update-source lo
 neighbor 192.168.255.12 bfd
 !
 address-family ipv4 unicast
  redistribute connected
  neighbor 192.168.255.11 activate
  neighbor 192.168.255.12 activate
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor 192.168.255.11 activate
  neighbor 192.168.255.12 activate
  advertise-all-vni
 exit-address-family
!
line vty
!
end
