frr version 10
frr defaults traditional
hostname ext-host3
!
interface lo
 ip address 192.168.255.15/32
!
interface lo-subnet
 ip address 10.70.0.1/24
!
interface eth1
 ip address 10.10.3.1/31
!
router bgp 65000
 bgp router-id 192.168.255.15
 no bgp ebgp-requires-policy
 neighbor 10.10.3.0 remote-as 65000
 !
 address-family ipv4 unicast
  redistribute connected
  neighbor 10.10.3.0 activate
 exit-address-family
!
line vty
!
end
