frr version 10.5.1_git
frr defaults traditional
hostname spine1
!
ip route 192.168.255.11/32 10.10.1.1
ip route 192.168.255.12/32 10.10.2.1
ip route 192.168.255.15/32 10.10.3.1
!
vrf tenant2-ipvrf
 ip route 10.70.0.0/24 10.10.3.1
 vni 201
exit-vrf
!
interface eth1
 ip address 10.10.1.0/31
exit
!
interface eth2
 ip address 10.10.2.0/31
exit
!
interface eth3
 ip address 10.10.3.0/31
exit
!
interface lo
 ip address 192.168.255.10/32
exit
!
interface lo-vtep
 ip address 100.64.0.10/32
exit
!
router bgp 65000
 bgp router-id 192.168.255.10
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 bgp cluster-id 192.168.255.10
 neighbor 192.168.255.11 remote-as internal
 neighbor 192.168.255.11 bfd
 neighbor 192.168.255.11 update-source lo
 neighbor 192.168.255.12 remote-as internal
 neighbor 192.168.255.12 bfd
 neighbor 192.168.255.12 update-source lo
 !
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor 192.168.255.11 activate
  neighbor 192.168.255.11 route-reflector-client
  neighbor 192.168.255.12 activate
  neighbor 192.168.255.12 route-reflector-client
  advertise-all-vni
 exit-address-family
exit
!
router bgp 65000 vrf tenant2-ipvrf
 no bgp ebgp-requires-policy
 no bgp network import-check
 neighbor 10.10.3.1 remote-as 65000
 !
 address-family ipv4 unicast
  network 10.60.0.0/24
  network 10.70.0.0/24
  redistribute connected
  redistribute static
  redistribute table 10
  import vpn
 exit-address-family
 !
 address-family l2vpn evpn
  advertise ipv4 unicast
  rd 192.168.255.10:201
  route-target import 65000:201
  route-target export 65000:201
 exit-address-family
exit
!
