frr version 10
frr defaults traditional
hostname spine1
!
interface eth1
 ip address 10.10.1.0/31
!
interface eth2
 ip address 10.10.2.0/31
!
router bgp 65413
 bgp router-id 10.10.1.0
 no bgp ebgp-requires-policy
 neighbor 10.10.1.1 remote-as 65001
 neighbor 10.10.2.1 remote-as 65002
 !
 address-family ipv4 unicast
  neighbor 10.10.1.1 activate
  neighbor 10.10.2.1 activate
 exit-address-family
!
line vty
!
end
